### ISSUE TITLE
Lagging animations/transitions

### ISSUE THREAD

**Issue by ayoits0913** [muslayev/icecat-win64#10]
Great job with these builds. The only issue I'm having now is certain animations are lagging. Scrolling through recent news on duckduckgo or loading animations on certain websites. It looks choppy, but seems fine on Waterfox. Are you aware of this or is it something on my end?

Here's an example: https://imgur.com/a/JdxZSMl

**Comment by muslayev** [comment]
Hi, thanks.
Yes, i have the same issue.
I suppose, it is a some bug related to hardware acceleration, here i found [libreplanet](https://libreplanet.org/wiki/Group:IceCat/icecat-help).
I faced, this pref gfx.direct2d.disabled is set to true by default in icecat.

**Comment by muslayev** [comment]
No, I am not right about pathes. Some pref in about:config harms animation. The main task is to determine which one :)
