### ISSUE TITLE
Unable to select another search engine

### ISSUE THREAD

**Issue by polandkraish** [muslayev/icecat-win64#12]
I can not add additional search engines except the default ones.

Not exactly a issue. But would be nice to add the option to put another search engine. 
At the moment I can not put Startpage as my default engine.

BTW, thanks for this great port for windows.

**Comment by ayoits0913** [comment]
Options > Search > Find more search engines (at the bottom)

**Comment by muslayev** [comment]
Put search field to the panel, open startpage.com, click on the "glass" icon and select.

![NoName1](https://user-images.githubusercontent.com/21295581/58757199-075a7480-852a-11e9-91fd-0262fcef9f4b.png)

**Comment by polandkraish** [comment]
@ayoits0913 method does not work since I simply cannot use another search engines - or install through the Mozilla add-ons website.  But using @muslayev method does work. Thanks. I prefer using the default address bar but is not rly a big issue.
