### ISSUE TITLE
NordVpn extension

### ISSUE THREAD

**Issue by ayoits0913** [muslayev/icecat-win64#13]
The latest extension that seemed to be compatible was  0.9.21 and it's terrible. Barely works. Any way to get the latest version working? I try to install and it says it appears to be corrupt

**Comment by Charadon** [comment]
This happens on icecat for a lot of add-ons. The fix is to remake the add-on by extracting the files, and adding this line in the manifest.json.
```  
"applications": {
      "gecko": {
          "id": "address@hidden"
      }
  },
```

**Comment by ayoits0913** [comment]
Thanks, but where do I add the line? At the bottom? And I have no idea how to repack it.

**Comment by ayoits0913** [comment]
Okay i just compressed to zip and renamed xpi? Still says corrupt.

**Comment by Charadon** [comment]
I did this fix on another add-on. Lemme show you its manifest.json as an example.
```
{

  "manifest_version": 2,
  "name": "Invidious Redirect",
  "version": "1.7",

  "description": "Redirects all YouTube links to Invidious. Previously hooktube-redirect.",
  
  "icons": {
    "48": "icons/hooktube-48.ico"
  },

  "applications": {
      "gecko": {
          "id": "address@hidden"
      }
  },	

  "content_scripts": [
    {
      "matches": ["*://*.youtube.com/*"],
      "run_at": "document_start",
      "js": ["makehook.js"]
    }
  ]

}
```
If this doesn't work, then sadly I can't help much more than that =(

**Comment by Charadon** [comment]
I decided to go ahead and try to do it myself. Use this manifest.json:
```
{
	
	"manifest_version":2,
	"name":"NordVPN Proxy Extension - Privacy & Security",
	"short_name":"Web Proxy",
	
	"description":"With this proxy extension, you can stay secure and private on the Internet and avoid those annoying online ads.",

	"icons": {
		"16":"./icons/nordvpn-16-active.png",
		"32":"./icons/nordvpn-32-active.png",
		"48":"./icons/nordvpn-48-active.png",
		"128":"./icons/nordvpn-128-active.png"
	},
	
	"applications": {
	   "gecko": {
             "id": "address@hidden"
      }
  },

	"browser_action": {
		"default_icon":"icons/nordvpn-48-inactive.png",
		"default_popup":"index.html","default_title":"NordVPN Browser Extension"
	},
	"permissions": ["proxy","webRequest","webRequestBlocking","privacy","<all_urls>","storage","idle","notifications","tabs"],
	"background": {
	"scripts":["background.bundle.js"]},
	"version":"2.11.1"
}
```
It was oddly all on one line, possible obfuscation? Not sure. But I tested it, and that should work.

**Comment by ayoits0913** [comment]
Thanks, yeah it was in one line. Still says corrupt for me though. Do you have the xpi file?

**Comment by ayoits0913** [comment]
Nevermind, got it working! My problem was i was trying to compress the parent folder of the add-ons instead of highlighting the individual items within then "add to archive." Tried that and it worked. Thanks again.

**Comment by muslayev** [comment]
Thank you too. In future, i will add your solution to main page. Recently, somebody asked me the same question.

**Comment by muslayev** [comment]
Added.
