### ISSUE TITLE
Tabs crashing often and vimeo videos not working

### ISSUE THREAD

**Issue by ayoits0913** [muslayev/icecat-win64#14]
Lately, my tabs have been crashing often. Is this a known issue? Happened with both Palemoon and now this.

Also, when trying to play a vimeo video embedded on a webpage, it says "Sorry. Because of its privacy settings, the video cannot be displayed here." and yet works on other browsers.

**Comment by muslayev** [comment]
Check it on latest ver: 68.0.2
