### ISSUE TITLE
manifest.json all in one line

### ISSUE THREAD

**Issue by ayoits0913** [muslayev/icecat-win64#15]
Since the previous thread was closed, guess I'll post it here.

I'm trying to download a couple themes and install them... and trying to follow Charadon's fix by copy/pasting to the manifest.json....except all of these themes/extensions i download have it in one line. I have no idea how it is supposed to be formatted.

https://addons.mozilla.org/en-US/firefox/addon/carbon-pro/?src=search

Love this browser though... any update coming soon?
![Screenshot_1](https://user-images.githubusercontent.com/50942242/59549497-ffe59300-8f4d-11e9-9666-b2109a8fe018.png)

**Comment by Charadon** [comment]
Yeah, the one line manifest.json's are incredibly annoying. So, basically, all information goes between the curly brackets. I'll use the nordvpn one as an example.
```
{
	
	"manifest_version":2,
	"name":"NordVPN Proxy Extension - Privacy & Security",
	"short_name":"Web Proxy",
	
	"description":"With this proxy extension, you can stay secure and private on the Internet and avoid those annoying online ads.",

	"icons": {
		"16":"./icons/nordvpn-16-active.png",
		"32":"./icons/nordvpn-32-active.png",
		"48":"./icons/nordvpn-48-active.png",
		"128":"./icons/nordvpn-128-active.png"
	},
	
	"applications": {
	   "gecko": {
             "id": "address@hidden"
      }
  },
```
If you take all of that, and put it in one line, all the stuff would be between the brackets. The issue isn't formating, but simply making it human readable. Hope this makes sense.

**Comment by ayoits0913** [comment]
The way the themes are set up seem to be a bit different? There are more brackets throughout and I'm still lost..
![Screenshot_1](https://user-images.githubusercontent.com/50942242/59555761-e3297980-8fa6-11e9-8b59-f2bd45b2e6fa.png)

**Comment by Charadon** [comment]
Yeah, it looks formatted correctly. Unforunately, I couldn't tell you where you inject the fix. Only advice I can give is that it'll most likely work if you paste the fix after the curly bracket before "verson"

**Comment by ayoits0913** [comment]
Didn't work, unfortunately. And there doesn't seem to be a way to get more themes

**Comment by ayoits0913** [comment]
Thanks for trying

**Comment by Charadon** [comment]
You might have better luck with Iceweasel than icecat. Icecat has some quirks.

**Comment by ayoits0913** [comment]
So this isn't something that can be fixed in an update? Also, is there a way to get themes (that actually work) besides the 3 that already come with it?

**Comment by muslayev** [comment]
> So this isn't something that can be fixed in an update? Also, is there a way to get themes (that actually work) besides the 3 that already come with it?

Actually, icecat depends on firefox ers releases. And mostly they include security fixes. 

https://wiki.mozilla.org/Enterprise/Firefox/ExtendedSupport:Proposal#Version_Numbers

**Comment by ayoits0913** [comment]
Thank you for fixing it. Themes and extensions work great now!

**Comment by muslayev** [comment]
> Thank you for fixing it. My theme installed perfectly fine but tried to install latest NordVPN extension and got the same corrupted error.

Now all extensions should work
