### ISSUE TITLE
Consider fix the addons & themes problem

### ISSUE THREAD

**Issue by misaka00251** [muslayev/icecat-win64#16]
https://raw.githubusercontent.com/kitsunyan/foxy-overlay/ace020013799a88c722e1b727b363fe2f06a5f61/www-client/icecat/files/fix-addons.patch

This patch will fix the installation of the addons which don't have ID(and Icecat will output "Cannot find ID for this addon").
Also, this will fix the theme install problem.

**Comment by muslayev** [comment]
Thanks, patch is applied https://github.com/muslayev/icecat-win64/releases/tag/v60.8.0

**Comment by misaka00251** [comment]
Can confirm the patch is working, thank you!
