### ISSUE TITLE
Where's the source code?

### ISSUE THREAD

**Issue by ekistece** [muslayev/icecat-win64#17]
You have only binaries on this repo, and that start.exe goes crazy on Virustotal. Are you compiling directly from GNU's source or are you modifying it?
https://www.virustotal.com/gui/file/fa4e00d844895e34cb58ee6f2ad7a7d57d2f8dca4989c98bd2b8ae997068d16c/detection

**Comment by muslayev** [comment]
start.exe is not a part of IceCat sources. Look here https://github.com/muslayev/icecat-win64/blob/master/misc/portable

and please read the note about start.exe in ReadMe of the current repository.
