### ISSUE TITLE
68.0.2 installer: "The system cannot find the file specified"

### ISSUE THREAD

**Issue by BurnyBoi** [muslayev/icecat-win64#19]
I'm getting an error when trying to run the Icecat 68.0.2 installer. It gets to 42%, then throws the error "The system cannot find the file specified." 

![2019-08-22 09_06_50-68 0](https://user-images.githubusercontent.com/41203525/63517058-c09f6980-c4dd-11e9-8f61-5879026f5bd9.jpg)

![2019-08-22 08_55_25-Issues · muslayev_icecat-win64 · GitHub - GNU IceCat](https://user-images.githubusercontent.com/41203525/63516387-5afead80-c4dc-11e9-86da-d8f6a46beb8f.jpg)

This occurs when running as Administrator as well. Any idea as to which file it is referring to in this case?

**Comment by muslayev** [comment]
Thanks, confirm it :( Look like installer [was not fixed](https://src.fedoraproject.org/rpms/icecat/c/692ae9d0fee6585895c4324ca7b39c7d0a8c25b9?branch=master) after moving to the new ESR branch.
I will recompile it.

**Comment by muslayev** [comment]
Fixed.
