### ISSUE TITLE
BitDefender found thread at your files 

### ISSUE THREAD

**Issue by 4nn0nym05** [muslayev/icecat-win64#2]
![virus](https://user-images.githubusercontent.com/42974724/45043347-74ed7900-b05c-11e8-9e1e-8101a373a5f2.png)
Found virus at bitdefender 

Edit: here is results from extracted archive virus is found in start.exe
![virus2](https://user-images.githubusercontent.com/42974724/45046916-15e13180-b067-11e8-81e5-33a56db0f1fe.png)

**Comment by muslayev** [comment]
"start.exe" was compiled to exe by this tool http://www.f2ko.de/en/b2e.php
You can delete start.exe and just use start.bat.

**Comment by 4nn0nym05** [comment]
Thanks for clarification, also I have discovered another problem that I will make new topic. T
Thank you
