### ISSUE TITLE
Unity supported but is disabled or blocked.

### ISSUE THREAD

**Issue by B3bomber** [muslayev/icecat-win64#22]
I used my profile and addons from Waterfox of the same ESR version and I know Unity worked on it. Not having any luck with Icecat though.

Any information you need I will try to provide.

**Comment by muslayev** [comment]
Hi, try to enable webgl support

![image](https://user-images.githubusercontent.com/21295581/65950623-3c3af180-e460-11e9-995f-1567da99f85e.png)

**Comment by B3bomber** [comment]
It is enabled. That's the problem...

**Comment by muslayev** [comment]
I tested it on 68.0.1 version. And checked it. Could you please provide the version?

**Comment by muslayev** [comment]
![2222222222](https://user-images.githubusercontent.com/21295581/66033602-67d5de80-e529-11e9-9f0c-6fcb9c12f62a.png)

**Comment by muslayev** [comment]
Also, please do not to use portable version, which doesn't contain libraries for 3d rendering.

**Comment by B3bomber** [comment]
I see, I'm using the 52 ESR portable version. I do not use anything but portable.

**Comment by muslayev** [comment]
> I see, I'm using the 52 ESR portable version. I do not use anything but portable.

You can download Installer and with 7zip extract all files to the application folder.

**Comment by B3bomber** [comment]
I'll go find that and give it a shot.

**Comment by B3bomber** [comment]
I think I figured out which files were need. It helps to get the correct file in the first place, though there's a bunch of extra stuff in it that isn't needed.

d3dcompiler_47.dll (this is a graphics file thingy for sure)

These 2 might be graphics related (webGL?)
libEGL.dll
libGLESv2.dll

That's all I ended up adding.
