### ISSUE TITLE
Portable version up to date?

### ISSUE THREAD

**Issue by MikeBlueberry** [muslayev/icecat-win64#25]
First of all, thank you so much for keeping this up to date, as humanly as possible as you do, much appreciated for your time and effort. I starred you.

My question relates to the **portable** version of your **IceCat** release for Windows. Is there one that you released that is up to date? 

Apologies if this is a dumb question.

**Comment by muslayev** [comment]
Hi, thanks.
Yes, i will update it after my vacation weeks.

**Comment by accounts1github** [comment]
Thank you, I love IceCat and what you're doing. Have a great vacation and come back fully rested.

**Comment by muslayev** [comment]
Done

**Comment by Tintin-Snowy** [comment]
> 
> 
> Done

You're awesome. Just checked you launched the new version.
