### ISSUE TITLE
Privacy settings are empty in 78.2.0

### ISSUE THREAD

**Issue by iamtherobin** [muslayev/icecat-win64#28]
When accessing about:preferences#privacy I get an empty settings window in 78.2.0 on Windows 7 x64. It works fine on 68.x.

It does this on my existing profile and a new profile.

**Comment by muslayev** [comment]
known issue for icecat 78~ versions due to unstable patches.

**Comment by tutak-kat** [comment]
Thanx for explanation, i have the same isssue.

**Comment by muslayev** [comment]
tutak-kat it would be good if somebody confirmed existing issue in linux

**Comment by tutak-kat** [comment]
Sorry I'am on win7 x64
-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


Sep 7, 2020, 20:23 by notifications@github.com:

**Comment by Marek33** [comment]
Is it possible to fix this issue somehow? I just tried the Iceweasel, which doesn't have it, but I do like the IceCat more, and since the weasel doesn't have that issue, I hope that the IceCat can be fixed as well.

**Comment by muslayev** [comment]
Fixed: https://github.com/muslayev/icecat-win64/releases/download/v78.2.0/icecat-78.2.0.en-US.win64.installer_fixed.exe

**Comment by iamtherobin** [comment]
Installed it. Still not change for me.

**Comment by muslayev** [comment]
please send md5 hash of icecat.exe from installed folder

**Comment by iamtherobin** [comment]
icecat.exe 645,632 bytes
MD5 58cd5b3e90ca035225972b3145a568a7

**Comment by muslayev** [comment]
Yes, please uninstall, and then install *_fixed.exe

**Comment by iamtherobin** [comment]
What I am saying, it is literally the same installer.

**Comment by muslayev** [comment]
Now works.

**Comment by Marek33** [comment]
Thanks, now it works!
