### ISSUE TITLE
Cannot save window size

### ISSUE THREAD

**Issue by hardhub** [muslayev/icecat-win64#29]
On next start the windows still not maximized (even if it was closed so).

**Comment by muslayev** [comment]
https://support.mozilla.org/en-US/questions/1262023#answer-1230360

**Comment by hardhub** [comment]
> 
> 
> https://support.mozilla.org/en-US/questions/1262023#answer-1230360

```
privacy.resistFingerprinting
```

So if I understand right it is enabled in IceCat by default?

**Comment by muslayev** [comment]
Yes. Is used to hide some unique data.

**Comment by hardhub** [comment]
OK, then let's close it.
