### ISSUE TITLE
Different User Agent

### ISSUE THREAD

**Issue by Marek33** [muslayev/icecat-win64#31]
Why is the user agent set to IceCat, and to the Netscape? On different websites I'm getting different results, so I don't know what to think of it. Considering that the **privacy.resist.fingerprinting** is turned on by default, shouldn't the user agent, be the same, as Firefox/Iceweasel has?

**Comment by muslayev** [comment]
The user agent of Icecat is exactly the same as Firefox ESR
![image](https://user-images.githubusercontent.com/21295581/94891039-cddda480-04a2-11eb-8f42-59aaaf99f5e1.png)

**Comment by Marek33** [comment]
Weird, I got this:
![Icecat UserAgent](https://user-images.githubusercontent.com/19204886/94915663-90cadf80-04ad-11eb-817c-7df247fe4187.jpg)
and this: 
![Privacy net](https://user-images.githubusercontent.com/19204886/94915765-c079e780-04ad-11eb-8d99-264f885ad472.jpg)

**Comment by muslayev** [comment]
Turn on / off **privacy.resistFingerprinting** 
And you will get Netscape of Firefox.

**Comment by Marek33** [comment]
I have Win7, and I have the same user agent, no matter, if I have it turned on or off. Shouldn't the privacy.resistFingerprinting says, that I use the Win10, like it does in Firefox, Waterfox or Iceweasel?

**Comment by muslayev** [comment]
privacy.resistFingerprinting is not responsible for the useragent.
Iceweasel uses librewolf config, which contains some setting to set win10 whatever you use.

Icecat has another settings supported by GNU community, and I have no idea what the settings are, i just make builds for windows and i'm not responsible for development.

**Comment by Marek33** [comment]
@muslayev For me, it is, on those three platforms, since it would normally show Win10 and not Win7. Also, it seems that the Fonts are different with the Icecat than the Firefox and Iceweasel, which are almost the same, except the Iceweasel doesn't have the Firefox telemetry.

I have removed that, so I don't think, that file affects it.

I see, and since there are no other builds for Windows, it would be good, if you could set the default user agent to the one, which you have, for those who have Win7, like me. The general.useragent.override only changes the user agent for the Header, but not for the JS.
