### ISSUE TITLE
Icecat Extensions

### ISSUE THREAD

**Issue by Marek33** [muslayev/icecat-win64#32]
Why is there these two extensions, which are not in the Iceweasel: LibreJS/USPS compatibility and Reveal hidden HTML? With extensions like _uBlock Origin_, _uMatrix_, _ClearURLs_, _Cookie Auto Delete_, _Decentraleyes_ and _HTTPS Everywhere_, I don't need any more extensions, so I want to know, if they will be removed in the new versions, and if not, why have them in the first place?

Explanation to remove them, moves me to this page, where is no info about it: https://libreplanet.org/wiki/Group:IceCat/cant-remove-addon

_The LibreJS may be useful, but I see no reason to use the Reveal hidden HTML._

**Comment by muslayev** [comment]
Because these extensions are part of Icecat.
Currently i see only two extensions are enabled, but folder contains more than two,
![image](https://user-images.githubusercontent.com/21295581/94890267-a4bc1480-04a0-11eb-8a30-7ebf67d77aa0.png)
It's because the extensions manifests are corrupted in source.

**Comment by Marek33** [comment]
I see, and what is the purpose of those extensions? And if I already have installed HTTPS Everywhere, do I need the one in the Icecat?

I see, and I didn't even know about that.

Yes, I did that as soon as I started using the Icecat, since the HTML notification, was quite annoying.

**Comment by muslayev** [comment]
>I see, and what is the purpose of those extensions?
Exctract *.xpi, open manifest.js with notepad and you will see "description" section.
>Everywhere, do I need the one in the Icecat?
You can delete it, anyway by priority icecat uses extensions from user folder

**Comment by Marek33** [comment]
Alright, and where is that folder?

And what if that one doesn't work?

**Comment by muslayev** [comment]
>Alright, and where is that folder?
\browser\extensions

**Comment by Marek33** [comment]
Thanks!
