### ISSUE TITLE
Update Firefox version

### ISSUE THREAD

**Issue by misaka00251** [muslayev/icecat-win64#33]
https://www.mozilla.org/en-US/firefox/78.9.0/releasenotes/

Nah maybe just use something to auto remind....

**Comment by MagicalDrizzle** [comment]
https://www.mozilla.org/en-US/firefox/78.6.0/releasenotes/

**Comment by MagicalDrizzle** [comment]
78.6.1 released, fixed critical security vulnerabilities
https://www.mozilla.org/en-US/security/advisories/mfsa2021-01/

**Comment by MagicalDrizzle** [comment]
78.7 released
https://www.mozilla.org/en-US/firefox/78.7.0/releasenotes/

**Comment by muslayev** [comment]
tomorrow
