### ISSUE TITLE
Cannot install Firefox Multi-account Containers addon

### ISSUE THREAD

**Issue by mimecry** [muslayev/icecat-win64#35]
Hi and thank you for the latest version 78.5. I'd like to report the following bug: when attempting to install the extension https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers on a new profile, i get this error message:
![image](https://user-images.githubusercontent.com/10742312/99362656-5941b680-28e6-11eb-921b-d486f77be9e1.png)

I figured that it might be due to either First Party Isolation or Resist Fingerprinting preferences, but neither seems to be the case. do you have any idea what preference or build setting is responsible for this?

**Comment by muslayev** [comment]
Looks like something is broken with [major commit](https://src.fedoraproject.org/rpms/icecat/c/474f89b317b877c4814462f473922ce993c7f53d?branch=master) 🙂
As option to resolve - downgrade the version to 78.4.0.

**Comment by mimecry** [comment]
hmm tried that and it still doesn't work, so i'm thinking it has to be due to a build option or flipped user preference

![image](https://user-images.githubusercontent.com/10742312/99378167-b430d900-28f9-11eb-90f8-41a42a59cb5f.png)

**Comment by muslayev** [comment]
>due to a build option or flipped user preference

I don't think so. Iceweasel was compiled with exactly the same build config, and doesn't have this issue. I suppose user preferences. Because i don't maitain preferences, it will be so hard to determine what option is wrong.

Noticed, since i started to build icecat, it had many problems with extensions. E.g., 78.5.0 is not abble to see built in extensions like LibreJs, therefore i removed it from package.

**Comment by muslayev** [comment]
Yes, the problem is in settings. I downloaded Firefox ESR, and added the settings from icecat and got your problem
![image](https://user-images.githubusercontent.com/21295581/99435788-d565e980-293a-11eb-96ac-dbfb44a6c208.png)

**Comment by muslayev** [comment]
Ok, go to about:config and set 
extensions.allowPrivateBrowsingByDefault as false

**Comment by mimecry** [comment]
perfect! thanks for looking into it boss
