### ISSUE TITLE
make this accessible for blind users with screen readers

### ISSUE THREAD

**Issue by paxcoder** [muslayev/icecat-win64#36]
please, make it accessible, NVDA dont reads anything here.

**Comment by muslayev** [comment]
do you mean icecat?

**Comment by paxcoder** [comment]
yeah.

**Comment by muslayev** [comment]
maybe will return in next release

**Comment by paxcoder** [comment]
Why the accessibility issue was closed?

**Comment by muslayev** [comment]
@paxcoder because it's not available on core level. I just release builds.
