### ISSUE TITLE
Cloudflare check infinite loop

### ISSUE THREAD

**Issue by DavidCreegan** [muslayev/icecat-win64#37]
I've disabled every setting, started the browser in safe mode, disabled enhanced tracking protection or ANY kind of protection but I still get an infinite loop when a website has Cloudflare and does a check of my browser..

**Comment by DavidCreegan** [comment]
And when I open the console when this is happening I see this:

Cookie “cf_chl_prog” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

This doesn't happen on any other browser so it's not the site

**Comment by DavidCreegan** [comment]
Tested on IceWeasel, works fine on there...just on IceCat it's an issue

**Comment by muslayev** [comment]
Could you give me the link?

**Comment by DavidCreegan** [comment]
Sure, it's iptorrents.com ... works fine on every other browser. It's probably like that for all cloudfare protected sites but idk any others to test

**Comment by muslayev** [comment]
You can't avoid it. Because some settings related to useragent were injected into omni.jar by icecat devs.

You can extract it in /browser and delete omni.jar.
Then open \browser\defaults\preferences\icecat.js and delete
pref("general.appname.override", "Netscape");
pref("general.appversion.override", "78.0");
pref("general.buildID.override", "Gecko/20100101");
pref("general.oscpu.override", "Windows NT 6.1");
pref("general.platform.override", "Win32");

Save, then try again.

**Comment by DavidCreegan** [comment]
There isn't any defaults folder for me in the browser folder, just extensions, features, and VisualElements. 

There is a defaults & prefs folder in the main install folder but the only file in that is channel-prefs.js. Also the omni file is .ja, not .jar. 

Idk what's going on. This is fresh install btw.

**Comment by DavidCreegan** [comment]
Worked like a charm! Does this affect anything else because I'm not quite sure what this did. And will future updates require me to repeat the process? Thanks for the help.

**Comment by muslayev** [comment]
I don't know what i will do for the next releases, because i provide builds withoud any changes from my side.

Also, i think you can download firefox esr, and find these strings in about:config and then owerride them in about:config of icecat.

**Comment by mimecry** [comment]
> 
> 
> I don't know what i will do for the next releases, because i provide builds withoud any changes from my side.
> 
> Also, i think you can download firefox esr, and find these strings in about:config and then override them in icecat's about:config

this is definitely the way to go, rather than editing omni.jar which will be overwritten on each upgrade

**Comment by DavidCreegan** [comment]
How do I do that exactly? Why would I need Firefox ESR for IceCat? Sorry, I'm confused

BTW, I can't download anything from Google Drive either. Not sure why. I tried with tracking disabled and disabled extensions, it does nothing when pressing download. I didn't think it was worth making a new topic on it, let me know if I should next time

Thanks

**Comment by muslayev** [comment]
@DavidCreegan accept all cookies.
