### ISSUE TITLE
Chocolatey

### ISSUE THREAD

**Issue by dimqua** [muslayev/icecat-win64#4]
Hi, I just added your installer build to the chocolatey repository for Windows.

https://chocolatey.org/packages/icecat

It seems that your portable build (60.2.2) does not have any addons pre-installed for some reason.

**Comment by dimqua** [comment]
@muslayev I can't find any references of 60.2.**2** version, for example, there is no such tag in the official repository: https://git.savannah.gnu.org/cgit/gnuzilla.git/refs/tags

Have you backported newer changes from Firefox ESR manually in this build?

**Comment by muslayev** [comment]
Here it: https://src.fedoraproject.org/rpms/icecat/c/d72091f75f3c9f4d7e52e098b7f96a34fad7de76

**Comment by dimqua** [comment]
@muslayev how you can explain these results?

[virustotal.com/file/b34e32ae732c915395b91142991fc371dfad724db5bd72219ec9d4e131702d78/analysis/](https://virustotal.com/file/b34e32ae732c915395b91142991fc371dfad724db5bd72219ec9d4e131702d78/analysis/)

Is this because of Bat To Exe Converter being used?

**Comment by muslayev** [comment]
Ok, i've just done it. I think it's false positive results.
I've extracted files from icecat-60.2.2.en-US.win64.installer.exe, then packed them and submitted to virustotal, as result, kaspersky and ms security didn't react.
Then second my stage:
I've deleted all cointaned files from installer via 7zip, and then submitted empty installer to virustotal, as result, kaspersky and ms security didn't react.

**Comment by dimqua** [comment]
Yes, I got the same results.

**Comment by muslayev** [comment]
added

**Comment by muslayev** [comment]
I've updated installer. I used this tutorial to make new installer:
https://superuser.com/posts/923281/revisions

And virustotal results,
https://www.virustotal.com/en/file/645fc30a8b9d527f417fa14fa534e2823f556d8e34b4c6d60821a0a348b7a4b4/analysis/

Unfortunately, i've deleted 60.2.2 as outdated.

**Comment by dimqua** [comment]
Thanks for letting me know.
