### ISSUE TITLE
Mozilla statement

### ISSUE THREAD

**Issue by muslayev** [muslayev/icecat-win64#42]
![image](https://user-images.githubusercontent.com/21295581/104093946-0b2eab00-52b8-11eb-9905-d31530636868.png)

Now you have another reason to not use farefox.

**Good choice:**
- IceCat
- [Ungoogled Chromium](https://ungoogled-software.github.io/ungoogled-chromium-binaries/)
- [Palemoon](https://www.palemoon.org/)
- [Brave](https://brave.com/)

**Comment by mimecry** [comment]
as a former long time user of Pale Moon, it suffered too much performance downgrade over time on an addon heavy profile. plus as it gradually phases out compatibility with legacy FF addons there'll be even less of an incentive to use it.

Brave has had its fair share of drama, i don't think you should recommend it as a privacy oriented alternative. 

Ungoogled Chromium is great but.. Chromium

Waterfox new version is quite buggy and the dev still can't figure out how to completely stop it from phoning home to Mozilla. can't recommend

best choices for browser imo are Firefox with heavily modified user.js (using https://github.com/arkenfox/user.js/ as a starting point), but if you don't care to do so then Icecat is a good choice :)  FF is my main browser at the moment and i have to say it absolutely obliterates Pale Moon in performance, with an even larger amount of addons installed

**Comment by Marek33** [comment]
The only good choice is IceCat. Iceweasel, with the IceCat improvements, would be the only second choice which I would use. Ungoogled Chromium, is an excellent browser as well, since it removes the Google spyware, but that's it. When the IceCat, would have a User agent and Fonts, same as, the Iceweasel, then it would be perfect.

**Comment by iamtherobin** [comment]
There is also LibreWolf now. It basically has the same goal in mind as Icecat which is to make Firefox not suck. There is no windows build yet. Which places it in the same boat as Icecat is right now. It will be interesting to see how it develops. I would love to try it myself on windows.

**Comment by mimecry** [comment]
last i checked, Librefox has some similar issues to Waterfox in that it's still phoning home to Mozilla addresses. and yeah, no windows build and doesn't seem there will be in the near future
