### ISSUE TITLE
Full URL not shown on DuckDuckGo search

### ISSUE THREAD

**Issue by Ziimmie** [muslayev/icecat-win64#43]
Hello,

I am having an issue where URLs are being trimmed on DuckDuckGo searches.  Attached is a example of this problem. This is a huge problem because if I go to a link from DuckDuckGo, and then go back, it lands me on the default DuckDuckGo page. It should be noted I have "browser.urlbar.trimURLs" set to false in about:config. Only extensions I have installed or uBlock Origin and Bitwarden.
![icecat_mDbmtX](https://user-images.githubusercontent.com/67846042/104481184-61079980-55bd-11eb-88a4-53fe6618b95d.png) 
![0wLmT5](https://user-images.githubusercontent.com/67846042/104481567-d5dad380-55bd-11eb-8a46-cf4fdbd19331.gif)

**Comment by mimecry** [comment]
remove the built in DDG engine and add a new one from Mycroft Project
