### ISSUE TITLE
Endless Cloudflare Loop

### ISSUE THREAD

**Issue by Nyanyanyanyan** [muslayev/icecat-win64#44]
Some cloudflare protected sites have an infinite browser checking loop, making them inaccessible with IceCat.
Other browsers work fine.
One of the sites in question: https://www.scribblehub.com/

**Comment by muslayev** [comment]
![image](https://user-images.githubusercontent.com/21295581/106352459-801c6000-630d-11eb-81f5-b63c84589b00.png)

**Comment by muslayev** [comment]
Recheck in 78.7.0
