### ISSUE TITLE
Add build instructions to the readme

### ISSUE THREAD

**Issue by humbletyrant** [muslayev/icecat-win64#45]
It would be helpful to add instructions on how to build Icecat on Windows so that others can build the package themselves. There is no information or documentation available anywhere on how to do this.

**Comment by muslayev** [comment]
All instructions you can find [here](https://firefox-source-docs.mozilla.org/contributing/contribution_quickref.html) no additions from my side.
Two main steps - install Visual Studio and download all dependencies with bootstrap command.

**Comment by humbletyrant** [comment]
The clarification is much appreciated.
