### ISSUE TITLE
Clear cookies exception lists not working as intended

### ISSUE THREAD

**Issue by iamtherobin** [muslayev/icecat-win64#49]
I been trying to configure Icecat to create a cookies whitelist without resorting to extensions. To do this I go to about:preferences#privacy and enable "Clear cookies and site data when Icecat is closed" and then I add domains to the exceptions list I want to keep.

I also make sure "Clear history when Icecat is closed" is configured to not clear cookies or site data to prevent inferring with the setup.

Using youtube.com for example:
I add youtube.com to the exception list and click save.
Then I login into youtube.com and verify the cookies show up in the list when I click "Manage Data" under the cookies settings.
I restart Icecat and check the cookies list in the "Manage Data" menu again and it is gone. I have to login into youtube.com again.

I tested this exact configuration in LibreWolf windows build and it works as intended. I can keep my youtube login when restarting librewolf in this example. So I do not know it if this is a Firefox ESR bug, an Icecat bug or a bug to this windows build.

**Comment by muslayev** [comment]
i reproduce your steps above with cleared icecat profile:
Restarted, and i see a data is still in the list:
![image](https://user-images.githubusercontent.com/21295581/120066777-e3d74f80-c099-11eb-86dd-19d8ff4dce82.png)

**Comment by iamtherobin** [comment]
Did you try to access youtube during the session? Mine shows the cookies are still there as well. But when I access the site, it is no longer logged in.

**Comment by muslayev** [comment]
> Did you try to access youtube during the session? Mine shows the cookies are still there as well. But when I access the site, it is no longer logged in.

Yes, with my gmail account i've seen my subscriptions.

**Comment by iamtherobin** [comment]
I just tried again with latest Icecat and a new profile. After restarting, the manage data shows cookies but no data stored. I have to login again. Now sure what is going on.
