### ISSUE TITLE
Privacy.resistFingerprinting is broken on Win7.

### ISSUE THREAD

**Issue by Marek33** [muslayev/icecat-win64#51]
The Mozilla, has finally fixed the Firefox 78 user agent, so it reports that one uses Win10, even if one uses Win7, but on IceCat, it still says that I have Win7.

Also, why is the BuildID set to the **Gecko/20100101** and not to the **20181001000000**? _I have changed it, in the about:config, but the User-agent, is not so easy to fix as that._

**Comment by muslayev** [comment]
UserAgent is hardcoded in omni.jar, so you neet to extract it and remove some strings.
Detailed info in readme.md.

**Comment by Marek33** [comment]
I understand, and I will wait for a new version then.

**Comment by Marek33** [comment]
Thanks for fixing the BuildID! Thou, the RFP is not yet fixed, and especially, why it's turned off in the latest version?

**Comment by Marek33** [comment]
Do you have some news about the UserAgent?

**Comment by muslayev** [comment]
> Thanks for fixing the BuildID! Thou, the RFP is not yet fixed, and especially, why it's turned off in the latest version?

it had torubles with some extensions (ads blocking for example) and with cloudflare.

**Comment by Marek33** [comment]
I see, and I don't see a problem with that, since if IceCat doesn't have a working RFP, then the whole point of privacy is gone, which is why, it's that important. Unfortunately, from what I have seen, the logo bug can't be fixed. By that, I mean this: https://thehackerblog.com/dirty-browser-enumeration-tricks-using-chrome-and-about-to-detect-firefox-plugins/index.html

So, unfortunately, at the end of the day, the Firefox is still the best private browser, even if I would absolutely love to stop using it.
