### ISSUE TITLE
How to enable widevine?

### ISSUE THREAD

**Issue by DavidCreegan** [muslayev/icecat-win64#53]
I know this may seem counterproductive as by default IceCat is DRM-free. But I want to watch some movies that require Widevine. And there are other reasons to use IceCat besides that.

Here's the thing...even when I try to install Widevine manually, it shows up for a second in the plugins as "disabled" and then is automatically removed.

I have browser.eme.ui.enabled and media.eme.enabled set to true so the DRM option shows up in preferences now but that doesn't change anything.

Some setting somewhere is removing Widevine immediately (and deleting it from appdata) and idk where it is .. if anyone could help I'd appreciate it

**Comment by muslayev** [comment]
Some GMP plugins don't have a support in Icecat. I found a way to enable only OpenH264 Video Codec.
