### ISSUE TITLE
Can't load any website when using AdNaseum

### ISSUE THREAD

**Issue by ayoits0913** [muslayev/icecat-win64#54]
This has been going on for a while... if I try to use Ad Naseum no website will load... this doesn't happen on Firefox or LibreWolf. Any fix?

**Comment by tutak-kat** [comment]
I can confirm this for portable Icecat, 
OS Win7x64

**Comment by ayoits0913** [comment]
I got it working with an old version 3.8.401

**Comment by muslayev** [comment]
user_pref("privacy.resistFingerprinting", false);
