### ISSUE TITLE
all cookie extensions not working 

### ISSUE THREAD

**Issue by baraa272** [muslayev/icecat-win64#56]
hello dev 
i tried many different cookie extensions but none of them working, also i tried to make a new profile but still fail 
it seems like its something related to patches OR default settings in icacat because cookie extensions are working in normal ESR

**Comment by muslayev** [comment]
please send me an extension name of one of them.

**Comment by baraa272** [comment]
cookie quick manager 
edit this cookie 2

**Comment by muslayev** [comment]
user_pref("privacy.resistFingerprinting", false);
then restart icecat

**Comment by baraa272** [comment]
still not working even after i restarted icecat with ("privacy.resistFingerprinting", false);
