### ISSUE TITLE
Windows Security reports Malware

### ISSUE THREAD

**Issue by gittn** [muslayev/icecat-win64#58]
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan:Win32/Zpevdo.B&threatid=2147729093

**Comment by muslayev** [comment]
which file?

**Comment by gittn** [comment]
icecat-78.12.0.en-US.win64.installer.exe
Probably the installer but it may be a packaged exe or dll inside it. No more info is provided.
You maybe caught a bug and it got in the installer when you made it?

Anyway I will take the opportunity to thank you for your work.

**Comment by muslayev** [comment]
You can exctract the installer (it has 7z format) and recheck it again. My installer is used from the beginning of my icecat project.
