### ISSUE TITLE
3-пати аддон + вопросик

### ISSUE THREAD

**Issue by bogachenko** [muslayev/icecat-win64#6]
Привет, не лучше ли сторонн~ие~юю ~плагины~ хрень выносить отдельно (я про это https://github.com/muslayev/icecat-win64#installer) а не включать ее в основной продукт? Да, я понимаю это неофиц. сборка, но все же? Что скажешь если в этом репозитории вместе с релизом ледяного котика публиковать этот аддон (+создать папку в этом репозитории где ты публикуешь фиксы)?

PS: что ты еще включил в сборку?

***
какое у тебя железо и сколько тратишь времени на сборку ледяного кота?

**Comment by muslayev** [comment]
Привет, пока пусть будет, до того момента, когда найду решение хостить xml файл с обновлениями. Ну а с xml можно уже через нативную службу обновляться. Больше я в сборку ничего не включал, а наоборот удалял - через флаги в mozconfig естественно, это всякие службы багрепортов, службы фонового обновления, вебдрайвер и прочая мелочь.

Насчет времени, я обычно на ночь ставлю и иду спать. Где-то 2 часа компилируется.

![Untitled](https://user-images.githubusercontent.com/21295581/56555246-26262c80-65b6-11e9-8e29-502e41b9f41f.png)

**Comment by bogachenko** [comment]
Блин, у тебя железо получше будет.

А как происходит компиляция, в смысле хочу вкатится в это (просто попробовать и удалить, поставить галочку - Я это сделал). Как это происходит? Какие программы ты используешь? Можешь расписать?

PS хотя я бы не расписывал, наверняка это долго (спроси ты меня такое, я бы нахуй послал)

**Comment by bogachenko** [comment]
есть какие нибудь гайды?

**Comment by muslayev** [comment]
> есть какие нибудь гайды?

Я делал по официальному гайду https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions/Windows_Prerequisites
Русский перевод можешь не смотреть, он не обновляется. Тут главное Visual Studio Community, MozillaBuild и установить [rust](https://www.rust-lang.org/tools/install) в систему. А так же по ходу компиляции устанавливать недостающие зависимости через cargo, которые будут видны в логе. Cargo это пакетный менеджер для rust. Лучше начать компилировать 65 версию лисы, потому что следующая версия лисы без каких-либо ошибок компилируется через clang.

**Comment by bogachenko** [comment]
спасибо, попробую
