### ISSUE TITLE
Missing dll file to run IceCat.

### ISSUE THREAD

**Issue by huhungahuru** [muslayev/icecat-win64#62]
IceCat depends on the MSVC library.
-https://community.chocolatey.org/packages/icecat#dependencies
-https://community.chocolatey.org/packages/vcredist140#files

When running IceCat there may be a missing dll error.
To fix this error you must install Microsoft Visual C++ Redistributable for Visual Studio 2015-2019.
-https://docs.microsoft.com/es-ES/cpp/windows/latest-supported-vc-redist?view=msvc-160
-x64: https://aka.ms/vs/16/release/vc_redist.x64.exe
-ARM64: https://aka.ms/vs/16/release/vc_redist.arm64.exe
-x86: https://aka.ms/vs/16/release/vc_redist.x86.exe

**Comment by muslayev** [comment]
Will not be fixed. As any other application, icecats needs some redistributable libraries.
