### ISSUE TITLE
Can't recover old Icecat Installation.

### ISSUE THREAD

**Issue by UltraJew** [muslayev/icecat-win64#63]
I recently reset my PC and with it I kept the Icecat install (ProgramFiles) to then later replace or use on my new Windows Installation again. This does work on Chromium but did not here, is there any way I can recover saved Logins or use the browser this way again?

**Comment by muslayev** [comment]
The chrome stores all data (including logins, history, bookmarks) on your google account.

Of course if you did a reset with saving your data in a separate folder (windows lets you choise an option), you can restore your lost data by moving the folder to the \AppData\Roaming\

**Comment by UltraJew** [comment]
I made a pretty big mistake it seems, I only backed up the ProgramFiles folder. I reset by using a bootable USB in my Bios. I'm not too hung up on any login data besides 1 or 2 select forum ones that I might be able to gain access to again. Thank you for the response still, I should've tried this method (specifically saving "\AppData\Roaming\mozilla\icecat") before making the reset.

**Comment by muslayev** [comment]
As workaround in future, just try to enable FF sync in Icecat:

set identity.fxaccounts.enabled to true in about:config
