### ISSUE TITLE
Any chance we get a 84 version? for those guys still use adobe flash player.

### ISSUE THREAD

**Issue by jasonliul** [muslayev/icecat-win64#64]
A greedy ask, v78.15.0 acutally works fine.
But if you may...

**Comment by muslayev** [comment]
No, you [can't](https://wiki.mozilla.org/Release_Management/Release_owners).

Icecat based on esr versions. After 78 version the next is 91 as esr.

**Comment by jasonliul** [comment]
Thank for suck quick reply, have a nice day.
