### ISSUE TITLE
Cloudflare DDoS check workaround, if someone still need it.

### ISSUE THREAD

**Issue by GarikTester** [muslayev/icecat-win64#65]
Go to about:config.

First, set the correct useragent (from Firefox ESR).

For the latest ESR, you can take on this site:
https://www.whatismybrowser.com/guides/the-latest-user-agent/

For Win 10, it should look like this (create string parameter, if not exist):
general.useragent.override     Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0

Then, bring these settings to following values (taken from actual vanilla Firefox).
general.appname.override       Netscape
general.appversion.override    5.0 (Windows)
general.buildID.override           2018100100
general.oscpu.override            Windows NT 10.0; Win64; x64
general.platform.override         Win32

Close about:config, relaunch Icecat.

**Comment by muslayev** [comment]
added to wiki
