### ISSUE TITLE
How did you compile?

### ISSUE THREAD

**Issue by jmkd3v** [muslayev/icecat-win64#67]
This is a duplicate of issue #66, which was deleted for seemingly no reason, along with almost every other issue.
The original contents of issue #66 were as follows:
> What the title says, I'm just curious about the process as I can't find instructions online, only links to your installer

**Comment by muslayev** [comment]
1) Download and install [Mozilla-Build](https://ftp.mozilla.org/pub/mozilla/libraries/win32/MozillaBuildSetup-Latest.exe)
2) Install [Visual Studio Community 2019](https://visualstudio.microsoft.com/downloads/), select "Desktop development with C++", "Windows 10 SDK", "C++ ATL" components
3) Download [Icecat sources](https://src.fedoraproject.org/lookaside/pkgs/icecat/)
4) Run start-shell.bat from **mozilla-build** folder, and go to the Icecat path
5) Run **./mach create-mach-environment**. And you will see ".mozbuild" folder in your profile folder. Just type path **%USERPROFILE%\.mozbuild** in Explorer.
6) Find and copy dependencies to the **%USERPROFILE%\.mozbuild** folder:
cbindgen
clang
glean
nasm
node
![image](https://user-images.githubusercontent.com/21295581/156637598-1583ad09-f46e-4f4b-a477-b93e3d129592.png)
7) Run **./mach build**

**Comment by jmkd3v** [comment]
Thank you so much for explaining - can you make sure that you don't delete the issue this time? I think many people will find this useful.

**Comment by muslayev** [comment]
I created a wiki. Will move it.

**Comment by tfriz343** [comment]
For clarity, I was the author of aforementioned issue #66.  And if I recall correctly, @muslayev had pointed me in the right direction, so I would consider that issue resolved.  Still, not exactly sure why it was removed from history, but that's the repo owner's decision.

Anyways, thank you @jmkd3v for inquiring about this again, and also huge thanks to @muslayev for the detailed writeup/wiki. ❤️

**Comment by jmkd3v** [comment]
> For clarity, I was the author of aforementioned issue #66

I believe the author of that issue was @iDenis124.

**Comment by muslayev** [comment]
@jmkd3v, @tfriz343, i created an easiest way for you:
https://github.com/muslayev/icecat-win64/wiki/How-to-compile

Check and rate.
