### ISSUE TITLE
бесконечная синхронизация

### ISSUE THREAD

**Issue by bogachenko** [muslayev/icecat-win64#8]
Короче, не могу синхронизироваться. Сначала думал, что роскомпараша опять поднасрала и забанила IP адреса, но нет. Я сменил свой ip на японский, проблема осталась. 
Кстати в Firefox такого нет. Проверял. 

Посмотри эту [гифку](https://user-images.githubusercontent.com/8535285/57385792-ce670280-71fe-11e9-9ee9-056fe0d81916.gif). Появляется слово "Working…" и дальше бесконечная загрузка.

Ждал мин 30.

**Comment by muslayev** [comment]
А на какой версии это, на предыдущем так же? Я в новом билде добавил новые флаги, которые удаляют из сборки IonMonkey JIT при компиляции.

**Comment by bogachenko** [comment]
На гифке твоя новая, которую ты 5 мин назад загрузил. В предыдущей так же.

**Comment by bogachenko** [comment]
кстати забавный факт. я **могу** войти в аккаунт на AMO, но не могу войти, чтобы синхронизироваться. пиздец

**Comment by bogachenko** [comment]
а у тебя повторяется? воспроизвести сможешь? аккаунт на AMO есть, чтобы синхронизировать?

**Comment by muslayev** [comment]
Тогда хрен понять, если до этого было все нормально. Возможно мозиловцы обновляют инфраструктуру из-за поломанных сертификатов и поломали синхронизацию в esr. Кстати, проверь в оригинальном ESR эту проблему.

Не, я синхронизацией не пользуюсь.

**Comment by muslayev** [comment]
http://www.opennet.ru/opennews/art.shtml?num=50647

Да, кстати, жди новую сборку, видать реально поломали старые сборки esr.

**Comment by bogachenko** [comment]
Сейчас проверю. Отпишусь.

**Comment by bogachenko** [comment]
Лол. Тоже не работает. Блять торmozilla не иначе. Ладно. Все равно спасибо.

**Comment by muslayev** [comment]
Не за что )))
