### ISSUE TITLE
Procedure for building an unofficial icecat on windows os

### ISSUE THREAD

**Issue by anon7847** [muslayev/icecat-win64#9]
Hello I'm sorry to bother but I need help.
I've been on this problem for days now and I'm running of patience (and time).
A thread was made on 8ch.net:
http://oxwugzccvk3dk6tj.onion/tech/res/1063167.html#q1065406
https://8ch.net/tech/res/1063167.html#q1065406
As explained in the thread following the mozilla guide wasn't successful to build Icecat on windows, it's pretty straight forward for GNU/linux but cross compile seems a dead end right now.
So could you please be kind enough to post a step by step list of how you did to build icecat for windows ?

Thank you for your time.

**Comment by muslayev** [comment]
Hi, as i understood, you are trying to use cross compiling, but i don't use linux. if you about windows host, It is not necessary to install each component as you did. Just install mozilla-build and add this line into mozconfig to disable STYLO dependencies. 
ac_add_options --disable-stylo
STYLO requires llvm.
And of course, i use vs community 2017 with these checked flags
![Uploading ddd.png…]()
And Firefox ESR is still using vs compiller. That is all.

**Comment by anon7847** [comment]
Thank you for your response. 
**you are trying to use cross compiling**
I did but not anymore what I tried recently was on a Windows 7 64bits operating system.

**It is not necessary to install each component as you did**
Understood..

**Just install mozilla-build and add this line into mozconfig to disable STYLO dependencies.**
Understood. Does the mozconfig has  to be located in the root of the icecat source code folder or somewhere else ?

**And of course, i use vs community 2017 with these checked flags**
I have remove VS community 2019 and installed the 2017 version with the same flags as you  but I'm still having errors so here's how I proceed.
-Installed visual studio 2017 community
-Installed the [mozilla build package](https://ftp.mozilla.org/pub/mozilla.org/mozilla/libraries/win32/MozillaBuildSetup-Latest.exe)
-Downloaded the [icecat source code](http://ftp.gnu.org/gnu/gnuzilla/60.3.0/)
-Extract it
-Open the **start-shell.bat** that was installed via the mozilla build package located in **C:\mozilla-build**
-Go to the location of the icecat source code **d:\maint\Desktop\icecat-60.3.0**
-make a mozconfig in the root of the folder of the source, with the same options as [your own mozconfi](https://github.com/muslayev/iceweasel-win64/blob/master/src/mozconfig) and of course I add the option to remove STYLO.
-Launch ./mach configure
-I get the error:
>0:10.11 ERROR: Rust compiler not found.
>0:10.11 To compile rust language sources, you must have 'rustc' in your path.
>0:10.11 See https://www.rust-lang.org/ for more information.
>0:10.11
>0:10.11 You can install rust by running './mach bootstrap'
>0:10.11 or by directly running the installer from https://rustup.rs/
>0:10.11
>0:10.20 *** Fix above errors and then restart with\
>0:10.20                "c:/mozilla-build/bin/mozmake.EXE -f client.mk build"
>0:10.22 mozmake.EXE: *** [client.mk:149: configure] Error

-I do ./mach bootstrap.py
-I select: 2. Icecat for desktop
-Everything is ok, rust installs itself then:
>Rust installation complete. You should now have rustc and cargo
in /c/Users/maintenance/.cargo/bin

-It then asks if I want to create the directory
>Would you like to create this directory?
-I choose 1
>Your choice: 1

-It then ask for to configure mercurial
>Would you like to run a configuration wizard to ensure Mercurial is
optimally configured?
-I choose 1
>Your choice: 1
Then this happens:
>Ensuring https://hg.mozilla.org/hgcustom/version-control-tools is up to date at
>c:/Users/maintenance/.mozbuild\version-control-tools
>(the full certificate chain may not be available locally; see "hg help debugssl"
>)
>abort: error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c
>:726)
>Error running mach:
>['bootstrap.py']

Here's the full dump of the terminal:
[error_bootstrap.txt](https://github.com/muslayev/icecat-win64/files/3213733/error_bootstrap.txt)

I don't understand what I'm doing wrong or missing.
I have found these discussions that seems similar to the problem that I have
https://bugzilla.mozilla.org/show_bug.cgi?id=1388213
https://bugzilla.mozilla.org/show_bug.cgi?id=1385888
The solution seems to be to disable STYLO, and that's what I do, like you suggested, I do add the line **ac_add_options --disable-stylo** to the mozconfig.


------------------------------------
By the way separately from this problem I have found something that can maybe help you.
In the section **Common problems, hints, and restrictions** in URL [Build_Instructions-Windows_Prerequisites](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions/Windows_Prerequisites) I have found this paragraphe:

> If you intend to distribute your build to others, set WIN32_REDIST_DIR=$VCINSTALLDIR\redist\x86\Microsoft.VC80.CRT in your mozconfig to get the Microsoft CRT DLLs packaged along with the application.

Wouldn't that option avoid to install the vcredist.exe separately ?

**Comment by muslayev** [comment]
Yes, you must have rust with cargo package manager. Instead bootstrap (i've never used that senseless command), just install cargo from here https://win.rustup.rs/. Then add cargo path in windows enviropment. Variable name is PATH, add this line at the end of existing line with ; separator.
;C:\Users\your_name\.cargo\bin
Restart terminal, and try ./mach build
Anyway he will show you some erors about missed libs - its ok, just install them via cargo package manager
cargo install some_missed_lib

> Wouldn't that option avoid to install the vcredist.exe separately ?
Yes i can, but for windows 10 theese libs are installed by default.
